---
- name: Create {{ user }} user
  hosts: relay
  user:
        name: {{ user }}
        comment: OctusBridge relayer
        group: admin

- name: Install relay
    hosts: relay
    become: True
    become_user: {{ user }}
    task:
      - name: Upgrade all packages
        apt:
          update_cache: true
          upgrade: full
          pkg: build-essential llvm clang git pkg-config openssl
          only_upgrade: true
      - name: Install rustup
        hurricanehrndz.rustup:
          rustup_user: {{ user }}
      - name: Clone relay repo
        git:
          repo: https://github.com/broxus/octusbridge-relay.git
          dest: {{ src_dir }}
          clone: yes
          update: yes
      - name: Build relay binary
        community.general.cargo:
          name: relay
          path: /
        environment:
          RUSTFLAGS: {{ rust_flags }}
      -	name: Copy relay systemd service
        copy:
          src: {{ src_dir }}/contrib/relay.native.service
          dest: /etc/systemd/system/relay.service
          owner: root
          group: root
          mode: '0644'
      - name: Enable systemd unit
        systemd:
          daemon_reload: true
          name: relay
          enabled: yes
      - name: Enable systemd unit
        systemd:
          name: systemd-timesyncd
          state: restarted

- name: Prepare relay
  hosts: relay
  become: True
  become_user: {{ user }}
  task:
    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        owner: relay
        group: relay
      loop:
        - {{ config_dir }}
        - {{ database_dir }}
    - name: Move relay config
      copy:
        src: {{ src_dir }}/contrib/config.yaml
        dest: {{ config_dir }}/
    - name: Get node config
      get_url: 
        url: {{ network_config_url }}
        dest: {{ config_dir }}/global.config.json
    - name: Generate config
      shell: 
        cmd: relay generate
    