---
- name: Deploy frontend
  hosts: frontend
  gather_facts: yes
  become: true
  vars_files:
    - vars/main.yml
    - vars/frontend.yml
  roles:
    - system
    - role: frontend
      become: true
      become_user: octusfront
  tags: [ "all" ]

- name: Deploy relayers
  hosts: relay
  gather_facts: yes
  become: true
  vars_files:
    - vars/main.yml
    - vars/relay.yml
  roles:
    - system
    - relay_install
    - relay_config
  tags: [ "all" ]

