---

- name: Setup system for frontend
  hosts: frontend
  gather_facts: yes
  vars_files:
    - vars/frontend.yml
  roles:
    - system
  tags: [ "all" ]

- name: Setup system for relayers
  hosts: relay
  gather_facts: yes
  vars_files:
    - vars/relay.yml
  roles:
    - system
  tags: [ "all" ]

- name: Deploy frontend
  hosts: frontend
  gather_facts: yes
  become: true
  become_user: {{ user }}
  vars_files:
    - vars/frontend.yml
  roles:
    - system
    - frontend
  tags: [ "all" ]

- name: Deploy relayers
  hosts: relay
  gather_facts: yes
  become: true
  become_user: {{ user }}
  vars_files:
    - vars/relay.yml
  roles:
    - hurricanehrndz.rustup
    - relay_install
    - relay_config
  tags: [ "all" ]

