---
- name: Clone git
  git:
    repo: https://github.com/broxus/octusbridge-frontend.git
    dest: "{{ src_dir }}"
    clone: true
    update: true

- name: Install dependencies
  npm:
    path: "{{ src_dir }}"
    ci: true

- name: Build and run
  command:
    chdir: "{{ src_dir }}"
    cmd: npm run start
  async: 1000
  poll: 0