---
- name: Clone git
  git:
    repo: https://github.com/broxus/octusbridge-frontend.git
    dest: "{{ src_dir }}"
    clone: true
    update: true

- name: Install dependencies
  npm:
    path: "{{ src_dir }}"
    ci: true

- name: Serve build
  command:
    chdir: "{{ src_dir }}"
    cmd: npm run build

- name: Start app
  command:
    chdir: "{{ src_dir }}"
    cmd: npm run start