- name: Add node repo
  shell: >
    curl -fsSL https://deb.nodesource.com/setup_{{ node_version }}.x | bash - &&\
  args:
    executable: /bin/bash

- name: Install system packages
  apt:
    name: "{{ apt_packages }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
